#!/bin/bash
#check if program is up to date ver 3

while true
do

while read line
do
	cd ~/hello/hello/$line
	if git remote show origin |& grep "local out of date"
	then 
		echo "$line out of date"
		git pull origin
		cp clientupdate updateclients checkgit ~/hello
		cd ~/hello/test
		if [ -s ~/hello/hello/$line/$line.erl ]
		then 
			echo "$line is an Erlang module"
			if erlc ~/hello/hello/$line/$line.erl |& grep "error"
			then
				echo "*** $line compile error, resetting to last version ***"
				while read auth
				do
					curl -u $auth -d '{"title": "Compile error","body": "Error compiling"}' https://api.github.com/repos/hkoskela/$line/issues
				done < ~/hello/auth.txt
				cd ~/hello/hello/$line
				git reset --hard HEAD@{1}
				cd ~/hello
			else
				echo "$line compiled OK"
				cd ~/hello/test
				mv $line.beam ~/hello
				cd ~/hello
			fi
		fi
		if [ -s ~/hello/hello/$line/$line.c ]
		then 
			echo "$line is a C++ program"
			if g++ ~/hello/hello/$line/$line.c -o $line |& grep "error"
			then
				echo "*** $line compile error, resetting to last version ***"
				while read auth
				do
					curl -u $auth -d '{"title": "Compile error","body": "Error compiling"}' https://api.github.com/repos/hkoskela/$line/issues
				done < ~/hello/auth.txt
				cd ~/hello/hello/$line
				git reset --hard HEAD@{1}
				cd ~/hello
			else
				echo "$line compiled OK"
				cd ~/hello/test
				mv $line ~/hello/helloc
				cp ~/hello/hello/$line/$line.ver ~/helloc
				cd ~/hello
			fi
		fi
	else
		echo "$line up to date"
		cd ~/hello
	fi
done < programs.txt
sleep 120
checkgit
done
