#!/bin/bash
#sending files to clients

if [ -s ~/hello/needupdate.txt ]
	then
		sed "s/'//g" ~/hello/needupdate.txt > ~/hello/needup.txt
		echo "needupdate.txt olemassa"
		sort ~/hello/needup.txt | uniq > ~/hello/temp.txt
		echo "needupdate -> temp"
		rm ~/hello/needup.txt
		rm ~/hello/needupdate.txt
		while read line 
		do
			echo "resending to $line"
			if scp -o ConnectTimeout=5 ~/hello/hello.beam $line:~/hello |& grep "lost connection"
			then
				echo "adding $line to needupdate"
				echo $line >> ~/hello/needupdate.txt
			else
				echo "sent to $line ok"
			fi
		done < ~/hello/temp.txt
		rm ~/hello/temp.txt
	else
		echo "No clients to update"
fi

if [ -s ~/hello/Cupdate.txt ]
	then
		sed "s/'//g" ~/hello/Cupdate.txt > ~/hello/Cup.txt
		echo "Cupdate.txt olemassa"
		sort ~/hello/Cup.txt | uniq > ~/hello/ctemp.txt
		echo "Cup -> ctemp"
		rm ~/hello/Cup.txt
		rm ~/hello/Cupdate.txt
		while read line 
		do
			echo "resending to $line"
			if scp -o ConnectTimeout=5 ~/hello/helloc/hello_c* $line:~/hello/helloc |& grep "lost connection"
			then
				echo "adding $line to Cupdate"
				echo $line >> ~/hello/Cupdate.txt
			else
				echo "sent to $line ok"
			fi
		done < ~/hello/ctemp.txt
		rm ~/hello/ctemp.txt
	else
		echo "No clients to update"
fi
